/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlebar.uinterface;

import controlebar.controller.BarController;
import java.util.ArrayList;



/**
 *
 * @author Diego Cansi Matte <diego.cansi at ibm.com>
 */
public class JanelaControleBar extends javax.swing.JFrame {

    private static final long serialVersionUID = 5662425693593388528L;
    private static BarController bar;

    /**
     * Creates new form JanelaControleBar
     */

    
    public JanelaControleBar() {
        initComponents();
        bar = new BarController();
    }
    
    public BarController getBar(){
        return bar;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton registrarClienteBotao = new javax.swing.JButton();
        encerrarBotao = new javax.swing.JButton();
        registrarSaida = new javax.swing.JButton();
        exibirClientesSociosBotao = new javax.swing.JButton();
        exibirGeneroBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de acesso ao bar");

        registrarClienteBotao.setActionCommand("registrarClienteBotao");
        registrarClienteBotao.setLabel("Registrar entrada de cliente");
        registrarClienteBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteBotaoActionPerformed(evt);
            }
        });

        encerrarBotao.setText("Encerrar sistema");
        encerrarBotao.setActionCommand("encerrarBotao");
        encerrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarBotaoActionPerformed(evt);
            }
        });

        registrarSaida.setText("Registrar saída de cliente");
        registrarSaida.setToolTipText("");
        registrarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarSaidaActionPerformed(evt);
            }
        });

        exibirClientesSociosBotao.setText("Exibir clientes e sócios");
        exibirClientesSociosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirClientesSociosBotaoActionPerformed(evt);
            }
        });

        exibirGeneroBotao.setText("Exibir por genero");
        exibirGeneroBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirGeneroBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exibirGeneroBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exibirClientesSociosBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encerrarBotao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarClienteBotao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(registrarClienteBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exibirClientesSociosBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exibirGeneroBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encerrarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarClienteBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteBotaoActionPerformed
        // TODO add your handling code here:
        JanelaRegistroEntrada jre = new JanelaRegistroEntrada(bar);
        jre.setVisible(true);    

    }//GEN-LAST:event_registrarClienteBotaoActionPerformed

    private void encerrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarBotaoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){  
                this.dispose();
                System.exit(0);
        }
    }//GEN-LAST:event_encerrarBotaoActionPerformed

    private void registrarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarSaidaActionPerformed
        // TODO add your handling code here:
        JanelaRegistroSaida jrs = new JanelaRegistroSaida(bar);
        jrs.setVisible(true);
    }//GEN-LAST:event_registrarSaidaActionPerformed

    private void exibirClientesSociosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirClientesSociosBotaoActionPerformed
        // TODO add your handling code here:
        ArrayList<String> lista = new ArrayList<String>();
        lista = getBar().mostraClientes();
        new JanelaExibeClientes(lista).setVisible(true);
    }//GEN-LAST:event_exibirClientesSociosBotaoActionPerformed

    private void exibirGeneroBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirGeneroBotaoActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showConfirmDialog(null,""+getBar().numeroClientesPorGeneroString(),"Número de Clientes por genero ",javax.swing.JOptionPane.CLOSED_OPTION );
    }//GEN-LAST:event_exibirGeneroBotaoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaControleBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaControleBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaControleBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaControleBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaControleBar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encerrarBotao;
    private javax.swing.JButton exibirClientesSociosBotao;
    private javax.swing.JButton exibirGeneroBotao;
    private javax.swing.JButton registrarSaida;
    // End of variables declaration//GEN-END:variables
}
