/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlebar.uinterface;

import controlebar.persistence.Cliente;
import controlebar.persistence.Socio;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author Diego Cansi Matte <diego.cansi at ibm.com>
 */
public class JanelaRegistroEntrada extends javax.swing.JFrame {

    private static final long serialVersionUID = -521418769005716983L;

    /**
     * Creates new form JanelaRegistroEntrada
     */
    
    public JanelaRegistroEntrada() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        nomeTexto = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        tituloJanelaTetxto = new javax.swing.JLabel();
        idadeTexto = new javax.swing.JLabel();
        idadeCampo = new javax.swing.JTextField();
        cpfTexto = new javax.swing.JLabel();
        cpfCampo = new javax.swing.JTextField();
        generoTexto = new javax.swing.JLabel();
        generoCampo = new javax.swing.JTextField();
        perguntaSocioTexto = new javax.swing.JLabel();
        socioRespostaCombo = new javax.swing.JComboBox<>();
        nroSocioTexto = new javax.swing.JLabel();
        nroSocioCampo = new javax.swing.JTextField();
        cadastrarBotao = new javax.swing.JButton();
        limparBotao = new javax.swing.JButton();
        voltarBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Registro");

        nomeTexto.setText("Nome: ");

        tituloJanelaTetxto.setBackground(new java.awt.Color(153, 153, 0));
        tituloJanelaTetxto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloJanelaTetxto.setText("Tela de registro de entrada de um novo cliente");

        idadeTexto.setText("Idade: ");

        idadeCampo.setToolTipText("");
        idadeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeCampoActionPerformed(evt);
            }
        });

        cpfTexto.setText("CPF: ");

        generoTexto.setText("Genero (H/M): ");

        perguntaSocioTexto.setText("Deseja colocar no programa de milhagens?");

        socioRespostaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        socioRespostaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioRespostaComboActionPerformed(evt);
            }
        });

        nroSocioTexto.setText("Número de sócio: ");
        nroSocioTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, socioRespostaCombo, org.jdesktop.beansbinding.ELProperty.create("${Sim}"), nroSocioTexto, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        nroSocioCampo.setEnabled(false);
        nroSocioCampo.setInheritsPopupMenu(true);
        nroSocioCampo.setName(""); // NOI18N
        nroSocioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroSocioCampoActionPerformed(evt);
            }
        });

        cadastrarBotao.setText("Cadastrar");
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });

        limparBotao.setText("Limpar");
        limparBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBotaoActionPerformed(evt);
            }
        });

        voltarBotao.setText("Voltar");
        voltarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generoTexto)
                        .addGap(18, 18, 18)
                        .addComponent(generoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpfTexto)
                        .addGap(18, 18, 18)
                        .addComponent(cpfCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idadeTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(nroSocioTexto)
                        .addGap(18, 18, 18)
                        .addComponent(nroSocioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(perguntaSocioTexto)
                                .addGap(18, 18, 18)
                                .addComponent(socioRespostaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrarBotao)
                                .addGap(18, 18, 18)
                                .addComponent(limparBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(voltarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloJanelaTetxto, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(tituloJanelaTetxto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTexto)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeTexto)
                    .addComponent(idadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTexto)
                    .addComponent(cpfCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoTexto)
                    .addComponent(generoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perguntaSocioTexto)
                    .addComponent(socioRespostaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroSocioTexto)
                    .addComponent(nroSocioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarBotao)
                    .addComponent(limparBotao)
                    .addComponent(voltarBotao))
                .addContainerGap())
        );

        nroSocioTexto.getAccessibleContext().setAccessibleName("Sim");
        nroSocioTexto.getAccessibleContext().setAccessibleParent(socioRespostaCombo);
        nroSocioCampo.getAccessibleContext().setAccessibleName("Sim");
        nroSocioCampo.getAccessibleContext().setAccessibleParent(socioRespostaCombo);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idadeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeCampoActionPerformed

    private void socioRespostaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioRespostaComboActionPerformed
        // TODO add your handling code here:

        socioRespostaCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                nroSocioCampo.setEnabled(false);

                if (e.getItem().toString().equals("Sim")) {
                    nroSocioCampo.setVisible(true);
                    nroSocioCampo.setEnabled(true);
                } else {
                    nroSocioCampo.setEnabled(false);
                }

            }
        });
    }//GEN-LAST:event_socioRespostaComboActionPerformed

    
    private void nroSocioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroSocioCampoActionPerformed
        // TODO add your handling code here:
        socioRespostaCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                nroSocioCampo.setEnabled(false);

                if (e.getItem().toString().equals("Sim")) {
                    nroSocioCampo.setVisible(true);
                    nroSocioCampo.setEnabled(true);
                } else {
                    nroSocioCampo.setEnabled(false);
                }

            }
        });
    }//GEN-LAST:event_nroSocioCampoActionPerformed

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoActionPerformed
        // TODO add your handling code here:
        String nome = nomeCampo.getText();
        int idade = Integer.parseInt(idadeCampo.getText());
        String cpf = cpfCampo.getText();
        String genero = generoCampo.getText();
        String resposta = socioRespostaCombo.getSelectedItem().toString();
        if(resposta.equals("Sim")){
            int nroSocio = Integer.parseInt(nroSocioCampo.getText());
            Socio s = new Socio(nome, cpf, idade, genero, nroSocio);
        } else {
            Cliente c = new Cliente(nome, cpf, idade, genero);
        }
        
    }//GEN-LAST:event_cadastrarBotaoActionPerformed

    private void limparBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBotaoActionPerformed
        // TODO add your handling code here:
        nroSocioCampo.setText("");
        generoCampo.setText("");
        idadeCampo.setText("");
        nomeCampo.setText("");
        cpfCampo.setText("");
    }//GEN-LAST:event_limparBotaoActionPerformed

    private void voltarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBotaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_voltarBotaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarBotao;
    private javax.swing.JTextField cpfCampo;
    private javax.swing.JLabel cpfTexto;
    private javax.swing.JTextField generoCampo;
    private javax.swing.JLabel generoTexto;
    private javax.swing.JTextField idadeCampo;
    private javax.swing.JLabel idadeTexto;
    private javax.swing.JButton limparBotao;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JLabel nomeTexto;
    private javax.swing.JTextField nroSocioCampo;
    private javax.swing.JLabel nroSocioTexto;
    private javax.swing.JLabel perguntaSocioTexto;
    private javax.swing.JComboBox<String> socioRespostaCombo;
    private javax.swing.JLabel tituloJanelaTetxto;
    private javax.swing.JButton voltarBotao;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
