/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlebar.uinterface;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author Diego Cansi Matte <diego.cansi at ibm.com>
 */
public class JanelaRegistroEntrada extends javax.swing.JFrame {

    /**
     * Creates new form JanelaRegistroEntrada
     */
    public JanelaRegistroEntrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        nomeTexto = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idadeTexto = new javax.swing.JLabel();
        idadeCampo = new javax.swing.JTextField();
        cpfTexto = new javax.swing.JLabel();
        cpfCampo = new javax.swing.JTextField();
        generoTexto = new javax.swing.JLabel();
        generoCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        socioRespostaCombo = new javax.swing.JComboBox<>();
        nroSocioTexto = new javax.swing.JLabel();
        nroSocioCampo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Registro");

        nomeTexto.setText("Nome: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tela de registro de entrada de um novo cliente");

        idadeTexto.setText("Idade: ");

        idadeCampo.setToolTipText("");
        idadeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeCampoActionPerformed(evt);
            }
        });

        cpfTexto.setText("CPF: ");

        generoTexto.setText("Genero (H/M): ");

        jLabel6.setText("Deseja colocar no programa de milhagens?");

        socioRespostaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        socioRespostaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioRespostaComboActionPerformed(evt);
            }
        });

        nroSocioTexto.setText("Número de sócio: ");
        nroSocioTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, socioRespostaCombo, org.jdesktop.beansbinding.ELProperty.create("${Sim}"), nroSocioTexto, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        nroSocioCampo.setInheritsPopupMenu(true);
        nroSocioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroSocioCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(socioRespostaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeTexto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generoTexto)
                                .addGap(18, 18, 18)
                                .addComponent(generoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfTexto)
                                .addGap(18, 18, 18)
                                .addComponent(cpfCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idadeTexto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(nroSocioTexto)
                        .addGap(18, 18, 18)
                        .addComponent(nroSocioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTexto)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeTexto)
                    .addComponent(idadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTexto)
                    .addComponent(cpfCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoTexto)
                    .addComponent(generoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(socioRespostaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroSocioTexto)
                    .addComponent(nroSocioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        nroSocioTexto.getAccessibleContext().setAccessibleName("Sim");
        nroSocioTexto.getAccessibleContext().setAccessibleParent(socioRespostaCombo);
        nroSocioCampo.getAccessibleContext().setAccessibleName("Sim");
        nroSocioCampo.getAccessibleContext().setAccessibleParent(socioRespostaCombo);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idadeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeCampoActionPerformed

    private void socioRespostaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioRespostaComboActionPerformed
        // TODO add your handling code here:
        
        socioRespostaCombo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                nroSocioCampo.setEnabled(false);
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    if (e.getItem().toString().equals("Sim")) {
                        nroSocioCampo.setVisible(true);
                        nroSocioCampo.setEnabled(true);
                    } else {
                        nroSocioCampo.setEnabled(false);
                    }
                }
            }
        });
    }//GEN-LAST:event_socioRespostaComboActionPerformed

    private void nroSocioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroSocioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nroSocioCampoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfCampo;
    private javax.swing.JLabel cpfTexto;
    private javax.swing.JTextField generoCampo;
    private javax.swing.JLabel generoTexto;
    private javax.swing.JTextField idadeCampo;
    private javax.swing.JLabel idadeTexto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JLabel nomeTexto;
    private javax.swing.JTextField nroSocioCampo;
    private javax.swing.JLabel nroSocioTexto;
    private javax.swing.JComboBox<String> socioRespostaCombo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
